import type {
  User, SellerProfile, Product, Order, Customer,
  FileAsset, Coupon, DownloadGrant, Subscription,
  AnalyticsEvent, EmailLog, PayoutRecord, Storefront,
  RefundStatus, AccessStatus,
} from '@/lib/domain/entities'
import { DEFAULT_SECTION_ORDER, DEFAULT_SECTION_VISIBILITY } from '@/lib/domain/entities'

// ─── USERS ──────────────────────────────────────────────────
export const DEMO_USERS: User[] = [
  {
    id: 'user-creator-1',
    email: 'creator@sellbop.demo',
    name: 'Alex Johnson',
    role: 'creator',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-buyer-1',
    email: 'buyer@sellbop.demo',
    name: 'Jordan Smith',
    role: 'buyer',
    createdAt: '2024-02-01T09:00:00Z',
  },
]

export const DEMO_CREDENTIALS: Record<string, string> = {
  'creator@sellbop.demo': 'demo123',
  'buyer@sellbop.demo': 'demo123',
}

// ─── SELLER PROFILE ─────────────────────────────────────────
export const DEMO_SELLER_PROFILE: SellerProfile = {
  id: 'seller-1',
  userId: 'user-creator-1',
  slug: 'alexjohnson',
  displayName: 'Alex Johnson',
  brandName: 'Alex Creates',
  bio: 'Creator, coach, and digital product designer helping people build intentional systems for life and work.',
  avatarUrl: null,
  logoUrl: null,
  websiteUrl: 'https://alexcreates.com',
  twitterUrl: 'https://twitter.com/alexcreates',
  supportEmail: 'creator@sellbop.demo',
  plan: 'pro',
  featuredProductIds: ['product-1', 'product-3', 'product-5'],
  themeColor: '#000000',
  createdAt: '2024-01-15T10:00:00Z',
}

export const DEMO_STOREFRONT: Storefront = {
  id: 'storefront-1',
  sellerId: 'seller-1',
  slug: 'alexjohnson',
  title: 'Alex Creates',
  headline: 'Digital products for creators who build with clarity.',
  bio: 'Creator, coach, and digital product designer. Everything I make is designed to help you work and live with clarity.',
  avatarUrl: null,
  bannerUrl: null,
  featuredProductIds: ['product-1', 'product-3', 'product-5'],
  productOrder: ['product-1', 'product-2', 'product-3', 'product-4', 'product-5', 'product-6'],
  hiddenProductIds: [],
  themeColor: '#000000',
  buttonStyle: 'rounded',
  cardStyle: 'soft_shadow',
  headerLayout: 'left_avatar',
  cardDensity: 'comfortable',
  sectionOrder: [...DEFAULT_SECTION_ORDER],
  sectionVisibility: { ...DEFAULT_SECTION_VISIBILITY },
  socialLinks: {
    twitter: 'https://twitter.com/alexcreates',
    website: 'https://alexcreates.com',
    instagram: 'https://instagram.com/alexcreates',
  },
  headerMedia: 'none',
  headerPhotoUrl: null,
  headerVideoUrl: null,
  published: true,
}

// ─── FILE ASSETS ────────────────────────────────────────────
export const DEMO_FILE_ASSETS: FileAsset[] = [
  {
    id: 'file-1',
    sellerId: 'seller-1',
    productId: 'product-1',
    name: 'Notion Template Pack',
    fileName: 'notion-template-pack-v2.zip',
    fileSize: 4200000,
    fileType: 'zip',
    mimeType: 'application/zip',
    storagePath: 'demo/notion-template-pack-v2.zip',
    downloadCount: 312,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'file-2',
    sellerId: 'seller-1',
    productId: 'product-2',
    name: 'Sermon Series Kit',
    fileName: 'sermon-series-kit.zip',
    fileSize: 18500000,
    fileType: 'zip',
    mimeType: 'application/zip',
    storagePath: 'demo/sermon-series-kit.zip',
    downloadCount: 148,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'file-3',
    sellerId: 'seller-1',
    productId: 'product-4',
    name: 'Creator Bundle - All Files',
    fileName: 'creator-bundle-complete.zip',
    fileSize: 52000000,
    fileType: 'zip',
    mimeType: 'application/zip',
    storagePath: 'demo/creator-bundle-complete.zip',
    downloadCount: 67,
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'file-4',
    sellerId: 'seller-1',
    productId: 'product-6',
    name: 'Church Media Pack - Vol 1',
    fileName: 'church-media-pack-vol1.zip',
    fileSize: 340000000,
    fileType: 'zip',
    mimeType: 'application/zip',
    storagePath: 'demo/church-media-pack-vol1.zip',
    downloadCount: 89,
    createdAt: '2024-02-15T10:00:00Z',
  },
  {
    id: 'file-5',
    sellerId: 'seller-1',
    productId: 'product-1',
    name: 'Quick Start Guide',
    fileName: 'notion-template-quick-start.pdf',
    fileSize: 1200000,
    fileType: 'pdf',
    mimeType: 'application/pdf',
    storagePath: 'demo/notion-template-quick-start.pdf',
    downloadCount: 289,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'file-6',
    sellerId: 'seller-1',
    productId: null,
    name: 'Brand Kit',
    fileName: 'alex-creates-brand-kit.zip',
    fileSize: 8900000,
    fileType: 'zip',
    mimeType: 'application/zip',
    storagePath: 'demo/brand-kit.zip',
    downloadCount: 0,
    createdAt: '2024-04-01T10:00:00Z',
  },
  {
    id: 'file-7',
    sellerId: 'seller-1',
    productId: 'product-2',
    name: 'Sermon Slides Template',
    fileName: 'sermon-slides-ppt.pptx',
    fileSize: 6800000,
    fileType: 'other',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    storagePath: 'demo/sermon-slides.pptx',
    downloadCount: 120,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'file-8',
    sellerId: 'seller-1',
    productId: 'product-4',
    name: 'Social Media Templates',
    fileName: 'social-media-templates.zip',
    fileSize: 22000000,
    fileType: 'zip',
    mimeType: 'application/zip',
    storagePath: 'demo/social-media-templates.zip',
    downloadCount: 55,
    createdAt: '2024-03-05T10:00:00Z',
  },
]

// ─── PRODUCTS ───────────────────────────────────────────────
export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'product-1',
    sellerId: 'seller-1',
    name: 'Notion Template Pack',
    slug: 'notion-template-pack',
    description: 'Everything you need to build a complete second brain in Notion. 50+ templates covering projects, goals, habits, journaling, finance tracking, and weekly reviews. Used by over 2,000 creators worldwide.',
    shortDescription: '50+ premium Notion templates for productivity, projects, and life systems.',
    productType: 'digital_download',
    status: 'published',
    price: 2900,
    compareAtPrice: 4900,
    currency: 'usd',
    thumbnailUrl: null,
    coverImageUrl: null,
    galleryImageUrls: [],
    category: 'Productivity',
    tags: ['notion', 'templates', 'productivity', 'second brain'],
    fileAssetIds: ['file-1', 'file-5'],
    externalUrl: null,
    confirmationMessage: 'Thank you! Your Notion templates are ready to download. Import them directly into Notion using the import links inside the ZIP file.',
    supportEmail: 'creator@sellbop.demo',
    ctaText: 'Get Instant Access',
    seoTitle: 'Notion Template Pack — 50+ Premium Templates',
    seoDescription: '50+ premium Notion templates for productivity, projects, and building a second brain.',
    licenseKeyEnabled: false,
    memberAccessEnabled: false,
    downloadLimit: null,
    accessExpirationDays: null,
    variants: [],
    salesCount: 312,
    viewCount: 4280,
    publishedAt: '2024-01-20T10:00:00Z',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
    marketplaceVisible: true,
    marketplaceExcerpt: '50+ premium Notion templates — projects, habits, journaling, finance, and more.',
  },
  {
    id: 'product-2',
    sellerId: 'seller-1',
    name: 'Sermon Series Kit',
    slug: 'sermon-series-kit',
    description: 'A complete toolkit for pastors and ministry leaders. Includes 12 sermon outline templates, Keynote/PowerPoint slide decks, bulletin inserts, social media graphics, and a series planning workbook.',
    shortDescription: 'Complete sermon series resources for pastors and ministry leaders.',
    productType: 'digital_download',
    status: 'published',
    price: 4900,
    compareAtPrice: 7900,
    currency: 'usd',
    thumbnailUrl: null,
    coverImageUrl: null,
    galleryImageUrls: [],
    category: 'Ministry',
    tags: ['sermon', 'church', 'ministry', 'pastor', 'templates'],
    fileAssetIds: ['file-2', 'file-7'],
    externalUrl: null,
    confirmationMessage: 'Thank you! Your Sermon Series Kit is ready. Check your email for access instructions.',
    supportEmail: 'creator@sellbop.demo',
    ctaText: 'Get the Kit',
    seoTitle: 'Sermon Series Kit — Complete Ministry Resources',
    seoDescription: 'Sermon outline templates, slide decks, and ministry resources for pastors.',
    licenseKeyEnabled: false,
    memberAccessEnabled: false,
    downloadLimit: 3,
    accessExpirationDays: 365,
    variants: [],
    salesCount: 148,
    viewCount: 1920,
    publishedAt: '2024-02-01T10:00:00Z',
    createdAt: '2024-01-28T10:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
    marketplaceVisible: true,
    marketplaceExcerpt: 'Complete sermon series resources: outlines, slides, bulletins, and social graphics.',
  },
  {
    id: 'product-3',
    sellerId: 'seller-1',
    name: '1-on-1 Coaching Call',
    slug: 'coaching-call',
    description: 'Book a 60-minute private coaching call with Alex. We\'ll dive deep into your current systems, goals, and challenges — and leave with a clear action plan. Great for creators, entrepreneurs, and anyone building something new.',
    shortDescription: '60-minute private coaching session with Alex Johnson.',
    productType: 'service_offer',
    status: 'published',
    price: 14900,
    compareAtPrice: null,
    currency: 'usd',
    thumbnailUrl: null,
    coverImageUrl: null,
    galleryImageUrls: [],
    category: 'Coaching',
    tags: ['coaching', 'consulting', '1on1', 'strategy'],
    fileAssetIds: [],
    externalUrl: 'https://cal.com/alexjohnson/coaching',
    confirmationMessage: 'Your session is booked! Use the link below to schedule your call time.',
    supportEmail: 'creator@sellbop.demo',
    ctaText: 'Book and Pay',
    seoTitle: '1-on-1 Coaching Call with Alex Johnson',
    seoDescription: 'Book a 60-minute private coaching session with Alex Johnson.',
    licenseKeyEnabled: false,
    memberAccessEnabled: false,
    downloadLimit: null,
    accessExpirationDays: null,
    variants: [],
    salesCount: 47,
    viewCount: 890,
    publishedAt: '2024-02-15T10:00:00Z',
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
    marketplaceVisible: true,
    marketplaceExcerpt: '60-minute private session to clarify your systems, goals, and next steps.',
  },
  {
    id: 'product-4',
    sellerId: 'seller-1',
    name: 'Creator Bundle',
    slug: 'creator-bundle',
    description: 'Everything in one place. The Creator Bundle includes the Notion Template Pack, Social Media Templates, Content Calendar, Email Swipe Files, and Branding Workbook. Save over 40% vs buying separately.',
    shortDescription: 'All of Alex\'s best digital products in one bundle. Save 40%.',
    productType: 'bundle',
    status: 'published',
    price: 7900,
    compareAtPrice: 13900,
    currency: 'usd',
    thumbnailUrl: null,
    coverImageUrl: null,
    galleryImageUrls: [],
    category: 'Bundle',
    tags: ['bundle', 'templates', 'creator', 'content'],
    fileAssetIds: ['file-3', 'file-8'],
    externalUrl: null,
    confirmationMessage: 'Welcome to the Creator Bundle! All files are ready for download below.',
    supportEmail: 'creator@sellbop.demo',
    ctaText: 'Get the Bundle',
    seoTitle: 'Creator Bundle — Alex\'s Complete Digital Toolkit',
    seoDescription: 'Save 40% with the Creator Bundle. Notion templates, social media assets, and more.',
    licenseKeyEnabled: false,
    memberAccessEnabled: false,
    downloadLimit: null,
    accessExpirationDays: null,
    variants: [],
    salesCount: 67,
    viewCount: 1420,
    publishedAt: '2024-03-05T10:00:00Z',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
    marketplaceVisible: true,
    marketplaceExcerpt: 'All of Alex\'s best products in one bundle — save over 40% vs buying separately.',
  },
  {
    id: 'product-5',
    sellerId: 'seller-1',
    name: 'Systems Membership',
    slug: 'systems-membership',
    description: 'Monthly access to Alex\'s Systems Lab. Get new templates every month, live Q&A sessions, private community access, and the complete archive of past resources. Cancel anytime.',
    shortDescription: 'Monthly templates, live sessions, and community access.',
    productType: 'subscription',
    status: 'published',
    price: 1900,
    compareAtPrice: null,
    currency: 'usd',
    thumbnailUrl: null,
    coverImageUrl: null,
    galleryImageUrls: [],
    category: 'Membership',
    tags: ['membership', 'subscription', 'community', 'templates'],
    fileAssetIds: [],
    externalUrl: null,
    confirmationMessage: 'Welcome to the Systems Lab! Check your email for access to the private community and resource vault.',
    supportEmail: 'creator@sellbop.demo',
    ctaText: 'Join the Lab',
    seoTitle: 'Systems Lab Membership — Monthly Templates and Sessions',
    seoDescription: 'Monthly membership with new templates, live Q&A, and community access.',
    licenseKeyEnabled: false,
    memberAccessEnabled: true,
    downloadLimit: null,
    accessExpirationDays: null,
    variants: [],
    salesCount: 89,
    viewCount: 2100,
    publishedAt: '2024-02-20T10:00:00Z',
    createdAt: '2024-02-18T10:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
    marketplaceVisible: true,
    marketplaceExcerpt: 'New templates monthly, live Q&A sessions, and private community. Cancel anytime.',
  },
  {
    id: 'product-6',
    sellerId: 'seller-1',
    name: 'Church Media Pack Vol. 1',
    slug: 'church-media-pack',
    description: 'Ready-to-use church media for your Sunday services. Includes motion backgrounds, title slides, lower thirds, announcements templates, and social media assets — all in 1080p and 4K.',
    shortDescription: 'Motion backgrounds, slides, and social graphics for your church.',
    productType: 'digital_download',
    status: 'published',
    price: 3900,
    compareAtPrice: 5900,
    currency: 'usd',
    thumbnailUrl: null,
    coverImageUrl: null,
    galleryImageUrls: [],
    category: 'Church Media',
    tags: ['church', 'media', 'video', 'worship', 'slides'],
    fileAssetIds: ['file-4'],
    externalUrl: null,
    confirmationMessage: 'Your Church Media Pack is ready! All files are available for download. Recommended software: ProPresenter, Keynote, or PowerPoint.',
    supportEmail: 'creator@sellbop.demo',
    ctaText: 'Download Now',
    seoTitle: 'Church Media Pack Vol. 1 — Motion Backgrounds and Slides',
    seoDescription: 'Professional church media: motion backgrounds, title slides, and social graphics.',
    licenseKeyEnabled: false,
    memberAccessEnabled: false,
    downloadLimit: 5,
    accessExpirationDays: 730,
    variants: [],
    salesCount: 89,
    viewCount: 1670,
    publishedAt: '2024-02-15T10:00:00Z',
    createdAt: '2024-02-12T10:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
    marketplaceVisible: true,
    marketplaceExcerpt: 'Professional motion backgrounds, slides, and social graphics for Sunday services.',
  },
]

// ─── CUSTOMERS ──────────────────────────────────────────────
export const DEMO_CUSTOMERS: Customer[] = [
  { id: 'cust-1', sellerId: 'seller-1', email: 'sarah.m@gmail.com', name: 'Sarah Mitchell', totalSpend: 18700, purchaseCount: 4, lastPurchaseAt: '2024-04-10T14:30:00Z', orderIds: ['order-1', 'order-5', 'order-11', 'order-17'], createdAt: '2024-01-22T10:00:00Z' },
  { id: 'cust-2', sellerId: 'seller-1', email: 'jared.k@outlook.com', name: 'Jared Kim', totalSpend: 14900, purchaseCount: 1, lastPurchaseAt: '2024-04-08T09:15:00Z', orderIds: ['order-2'], createdAt: '2024-04-08T09:00:00Z' },
  { id: 'cust-3', sellerId: 'seller-1', email: 'pastor.dave@grace.church', name: 'David Reyes', totalSpend: 9800, purchaseCount: 2, lastPurchaseAt: '2024-04-05T11:45:00Z', orderIds: ['order-3', 'order-12'], createdAt: '2024-02-03T10:00:00Z' },
  { id: 'cust-4', sellerId: 'seller-1', email: 'maya.c@icloud.com', name: 'Maya Chen', totalSpend: 7900, purchaseCount: 1, lastPurchaseAt: '2024-04-03T16:20:00Z', orderIds: ['order-4'], createdAt: '2024-04-03T16:00:00Z' },
  { id: 'cust-5', sellerId: 'seller-1', email: 'brandon.t@gmail.com', name: 'Brandon Torres', totalSpend: 5800, purchaseCount: 2, lastPurchaseAt: '2024-04-01T10:00:00Z', orderIds: ['order-6', 'order-14'], createdAt: '2024-03-10T10:00:00Z' },
  { id: 'cust-6', sellerId: 'seller-1', email: 'lisa.w@yahoo.com', name: 'Lisa Wang', totalSpend: 4900, purchaseCount: 1, lastPurchaseAt: '2024-03-28T14:00:00Z', orderIds: ['order-7'], createdAt: '2024-03-28T14:00:00Z' },
  { id: 'cust-7', sellerId: 'seller-1', email: 'mike.j@gmail.com', name: 'Mike Johnson', totalSpend: 2900, purchaseCount: 1, lastPurchaseAt: '2024-03-25T09:30:00Z', orderIds: ['order-8'], createdAt: '2024-03-25T09:00:00Z' },
  { id: 'cust-8', sellerId: 'seller-1', email: 'pastor.sue@newlife.org', name: 'Susan Park', totalSpend: 8800, purchaseCount: 2, lastPurchaseAt: '2024-03-20T13:00:00Z', orderIds: ['order-9', 'order-15'], createdAt: '2024-02-20T10:00:00Z' },
  { id: 'cust-9', sellerId: 'seller-1', email: 'ryan.b@gmail.com', name: 'Ryan Brooks', totalSpend: 1900, purchaseCount: 1, lastPurchaseAt: '2024-03-15T11:00:00Z', orderIds: ['order-10'], createdAt: '2024-03-15T11:00:00Z' },
  { id: 'cust-10', sellerId: 'seller-1', email: 'jordan@sellbop.demo', name: 'Jordan Smith', totalSpend: 13700, purchaseCount: 3, lastPurchaseAt: '2024-04-12T08:00:00Z', orderIds: ['order-13', 'order-16', 'order-18'], createdAt: '2024-02-01T09:00:00Z' },
]

// ─── ORDERS ─────────────────────────────────────────────────
type MkOrderInput = Omit<Order, 'refundStatus'|'refundedAt'|'refundReason'|'accessStatus'|'subscriptionId'|'internalNotes'> & Partial<Pick<Order,'refundStatus'|'refundedAt'|'refundReason'|'accessStatus'|'subscriptionId'|'internalNotes'>>

function mkOrder(o: MkOrderInput): Order {
  const defaults: Pick<Order,'refundStatus'|'refundedAt'|'refundReason'|'accessStatus'|'subscriptionId'|'internalNotes'> = {
    refundStatus: o.paymentStatus === 'refunded' ? 'refunded' : 'paid' as RefundStatus,
    refundedAt: null,
    refundReason: null,
    accessStatus: o.paymentStatus === 'refunded' ? 'revoked' : 'active' as AccessStatus,
    subscriptionId: null,
    internalNotes: null,
  }
  return { ...defaults, ...o }
}

export const DEMO_ORDERS: Order[] = [
  mkOrder({ id: 'order-1',  sellerId: 'seller-1', productId: 'product-3', productName: '1-on-1 Coaching Call',       productType: 'service_offer',   customerId: 'cust-1',  customerEmail: 'sarah.m@gmail.com',        customerName: 'Sarah Mitchell',  amount: 14900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-10T14:30:00Z' }),
  mkOrder({ id: 'order-2',  sellerId: 'seller-1', productId: 'product-3', productName: '1-on-1 Coaching Call',       productType: 'service_offer',   customerId: 'cust-2',  customerEmail: 'jared.k@outlook.com',      customerName: 'Jared Kim',       amount: 14900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-08T09:15:00Z' }),
  mkOrder({ id: 'order-3',  sellerId: 'seller-1', productId: 'product-2', productName: 'Sermon Series Kit',          productType: 'digital_download',customerId: 'cust-3',  customerEmail: 'pastor.dave@grace.church', customerName: 'David Reyes',     amount:  4900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-05T11:45:00Z' }),
  mkOrder({ id: 'order-4',  sellerId: 'seller-1', productId: 'product-4', productName: 'Creator Bundle',             productType: 'bundle',          customerId: 'cust-4',  customerEmail: 'maya.c@icloud.com',        customerName: 'Maya Chen',       amount:  7900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: 'coupon-2', couponCode: 'CREATOR20', discountAmount: 1000, stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-03T16:20:00Z' }),
  mkOrder({ id: 'order-5',  sellerId: 'seller-1', productId: 'product-1', productName: 'Notion Template Pack',       productType: 'digital_download',customerId: 'cust-1',  customerEmail: 'sarah.m@gmail.com',        customerName: 'Sarah Mitchell',  amount:  2900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-02T08:00:00Z' }),
  mkOrder({ id: 'order-6',  sellerId: 'seller-1', productId: 'product-1', productName: 'Notion Template Pack',       productType: 'digital_download',customerId: 'cust-5',  customerEmail: 'brandon.t@gmail.com',      customerName: 'Brandon Torres',  amount:  2900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-01T10:00:00Z' }),
  mkOrder({ id: 'order-7',  sellerId: 'seller-1', productId: 'product-2', productName: 'Sermon Series Kit',          productType: 'digital_download',customerId: 'cust-6',  customerEmail: 'lisa.w@yahoo.com',         customerName: 'Lisa Wang',       amount:  4900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-03-28T14:00:00Z' }),
  mkOrder({ id: 'order-8',  sellerId: 'seller-1', productId: 'product-1', productName: 'Notion Template Pack',       productType: 'digital_download',customerId: 'cust-7',  customerEmail: 'mike.j@gmail.com',         customerName: 'Mike Johnson',    amount:  2900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: 'coupon-1', couponCode: 'WELCOME10', discountAmount: 290,  stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-03-25T09:30:00Z' }),
  mkOrder({ id: 'order-9',  sellerId: 'seller-1', productId: 'product-6', productName: 'Church Media Pack Vol. 1',   productType: 'digital_download',customerId: 'cust-8',  customerEmail: 'pastor.sue@newlife.org',   customerName: 'Susan Park',      amount:  3900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-03-20T13:00:00Z' }),
  mkOrder({ id: 'order-10', sellerId: 'seller-1', productId: 'product-5', productName: 'Systems Membership',         productType: 'subscription',    customerId: 'cust-9',  customerEmail: 'ryan.b@gmail.com',         customerName: 'Ryan Brooks',     amount:  1900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-03-15T11:00:00Z', subscriptionId: 'sub-1' }),
  mkOrder({ id: 'order-11', sellerId: 'seller-1', productId: 'product-5', productName: 'Systems Membership',         productType: 'subscription',    customerId: 'cust-1',  customerEmail: 'sarah.m@gmail.com',        customerName: 'Sarah Mitchell',  amount:  1900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-03-10T10:00:00Z', subscriptionId: 'sub-2' }),
  mkOrder({ id: 'order-12', sellerId: 'seller-1', productId: 'product-6', productName: 'Church Media Pack Vol. 1',   productType: 'digital_download',customerId: 'cust-3',  customerEmail: 'pastor.dave@grace.church', customerName: 'David Reyes',     amount:  3900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-03-08T14:00:00Z' }),
  mkOrder({ id: 'order-13', sellerId: 'seller-1', productId: 'product-1', productName: 'Notion Template Pack',       productType: 'digital_download',customerId: 'cust-10', customerEmail: 'jordan@sellbop.demo',      customerName: 'Jordan Smith',    amount:  2900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-02-28T09:00:00Z' }),
  mkOrder({ id: 'order-14', sellerId: 'seller-1', productId: 'product-2', productName: 'Sermon Series Kit',          productType: 'digital_download',customerId: 'cust-5',  customerEmail: 'brandon.t@gmail.com',      customerName: 'Brandon Torres',  amount:  4900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-02-22T11:00:00Z' }),
  mkOrder({ id: 'order-15', sellerId: 'seller-1', productId: 'product-2', productName: 'Sermon Series Kit',          productType: 'digital_download',customerId: 'cust-8',  customerEmail: 'pastor.sue@newlife.org',   customerName: 'Susan Park',      amount:  4900, currency: 'usd', status: 'refunded',  paymentStatus: 'refunded', couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-02-15T14:00:00Z', refundedAt: '2024-02-16T10:00:00Z', refundReason: 'Customer requested refund — content not as described.', accessStatus: 'revoked' }),
  mkOrder({ id: 'order-16', sellerId: 'seller-1', productId: 'product-4', productName: 'Creator Bundle',             productType: 'bundle',          customerId: 'cust-10', customerEmail: 'jordan@sellbop.demo',      customerName: 'Jordan Smith',    amount:  7900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-02-10T10:00:00Z' }),
  mkOrder({ id: 'order-17', sellerId: 'seller-1', productId: 'product-5', productName: 'Systems Membership',         productType: 'subscription',    customerId: 'cust-1',  customerEmail: 'sarah.m@gmail.com',        customerName: 'Sarah Mitchell',  amount:  1900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-02-10T09:00:00Z', subscriptionId: 'sub-2' }),
  mkOrder({ id: 'order-18', sellerId: 'seller-1', productId: 'product-3', productName: '1-on-1 Coaching Call',       productType: 'service_offer',   customerId: 'cust-10', customerEmail: 'jordan@sellbop.demo',      customerName: 'Jordan Smith',    amount: 14900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-12T08:00:00Z' }),
  mkOrder({ id: 'order-19', sellerId: 'seller-1', productId: 'product-1', productName: 'Notion Template Pack',       productType: 'digital_download',customerId: 'cust-7',  customerEmail: 'mike.j@gmail.com',         customerName: 'Mike Johnson',    amount:  2900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-13T07:30:00Z' }),
  mkOrder({ id: 'order-20', sellerId: 'seller-1', productId: 'product-6', productName: 'Church Media Pack Vol. 1',   productType: 'digital_download',customerId: 'cust-4',  customerEmail: 'maya.c@icloud.com',        customerName: 'Maya Chen',       amount:  3900, currency: 'usd', status: 'completed', paymentStatus: 'paid',     couponId: null,       couponCode: null,        discountAmount: 0,    stripePaymentIntentId: null, stripeSessionId: null, receiptSent: true, createdAt: '2024-04-14T15:00:00Z' }),
]

// ─── COUPONS ────────────────────────────────────────────────
export const DEMO_COUPONS: Coupon[] = [
  { id: 'coupon-1', sellerId: 'seller-1', code: 'WELCOME10', type: 'percent', value: 10, maxUses: 100, usedCount: 43, active: true, expiresAt: null, productIds: null, createdAt: '2024-01-15T10:00:00Z' },
  { id: 'coupon-2', sellerId: 'seller-1', code: 'CREATOR20', type: 'percent', value: 20, maxUses: 50, usedCount: 12, active: true, expiresAt: '2024-12-31T23:59:59Z', productIds: ['product-4'], createdAt: '2024-03-01T10:00:00Z' },
  { id: 'coupon-3', sellerId: 'seller-1', code: 'CHURCH15', type: 'fixed', value: 1500, maxUses: null, usedCount: 8, active: true, expiresAt: null, productIds: ['product-2', 'product-6'], createdAt: '2024-02-15T10:00:00Z' },
  { id: 'coupon-4', sellerId: 'seller-1', code: 'LAUNCH50', type: 'percent', value: 50, maxUses: 20, usedCount: 20, active: false, expiresAt: '2024-02-28T23:59:59Z', productIds: null, createdAt: '2024-01-15T10:00:00Z' },
]

// ─── SUBSCRIPTIONS ──────────────────────────────────────────
export const DEMO_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-1', sellerId: 'seller-1', customerId: 'cust-9', customerName: 'Ryan Brooks',
    productId: 'product-5', productName: 'Systems Membership',
    customerEmail: 'ryan.b@gmail.com', status: 'active',
    currentPeriodStart: '2024-04-15T00:00:00Z', currentPeriodEnd: '2024-05-15T00:00:00Z',
    cancelAtPeriodEnd: false, canceledAt: null, cancelMode: null,
    accessStatus: 'active', latestPaymentStatus: 'paid',
    amount: 1900, currency: 'usd', stripeSubscriptionId: null,
    internalNotes: null, createdAt: '2024-03-15T11:00:00Z',
  },
  {
    id: 'sub-2', sellerId: 'seller-1', customerId: 'cust-1', customerName: 'Sarah Mitchell',
    productId: 'product-5', productName: 'Systems Membership',
    customerEmail: 'sarah.m@gmail.com', status: 'active',
    currentPeriodStart: '2024-04-10T00:00:00Z', currentPeriodEnd: '2024-05-10T00:00:00Z',
    cancelAtPeriodEnd: false, canceledAt: null, cancelMode: null,
    accessStatus: 'active', latestPaymentStatus: 'paid',
    amount: 1900, currency: 'usd', stripeSubscriptionId: null,
    internalNotes: null, createdAt: '2024-02-10T09:00:00Z',
  },
  {
    id: 'sub-3', sellerId: 'seller-1', customerId: 'cust-10', customerName: 'Jordan Smith',
    productId: 'product-5', productName: 'Systems Membership',
    customerEmail: 'jordan@sellbop.demo', status: 'canceled',
    currentPeriodStart: '2024-03-01T00:00:00Z', currentPeriodEnd: '2024-04-01T00:00:00Z',
    cancelAtPeriodEnd: true, canceledAt: '2024-03-20T10:00:00Z', cancelMode: 'cancel_end_of_period',
    accessStatus: 'revoked', latestPaymentStatus: 'paid',
    amount: 1900, currency: 'usd', stripeSubscriptionId: null,
    internalNotes: 'Buyer canceled via buyer portal.', createdAt: '2024-02-01T09:00:00Z',
  },
  {
    id: 'sub-4', sellerId: 'seller-1', customerId: 'cust-5', customerName: 'Brandon Torres',
    productId: 'product-5', productName: 'Systems Membership',
    customerEmail: 'brandon.t@gmail.com', status: 'past_due',
    currentPeriodStart: '2024-04-01T00:00:00Z', currentPeriodEnd: '2024-05-01T00:00:00Z',
    cancelAtPeriodEnd: false, canceledAt: null, cancelMode: null,
    accessStatus: 'active', latestPaymentStatus: 'failed',
    amount: 1900, currency: 'usd', stripeSubscriptionId: null,
    internalNotes: null, createdAt: '2024-03-01T09:00:00Z',
  },
]

// ─── DOWNLOAD GRANTS ────────────────────────────────────────
export const DEMO_DOWNLOAD_GRANTS: DownloadGrant[] = [
  { id: 'dl-1', orderId: 'order-5', productId: 'product-1', fileAssetId: 'file-1', buyerEmail: 'sarah.m@gmail.com', token: 'demo-token-abc123', downloadCount: 2, maxDownloads: null, expiresAt: null, createdAt: '2024-04-02T08:01:00Z' },
  { id: 'dl-2', orderId: 'order-3', productId: 'product-2', fileAssetId: 'file-2', buyerEmail: 'pastor.dave@grace.church', token: 'demo-token-def456', downloadCount: 1, maxDownloads: 3, expiresAt: '2025-04-05T11:45:00Z', createdAt: '2024-04-05T11:46:00Z' },
  { id: 'dl-3', orderId: 'order-13', productId: 'product-1', fileAssetId: 'file-1', buyerEmail: 'jordan@sellbop.demo', token: 'demo-token-ghi789', downloadCount: 0, maxDownloads: null, expiresAt: null, createdAt: '2024-02-28T09:01:00Z' },
]

// ─── EMAIL LOGS ─────────────────────────────────────────────
export const DEMO_EMAIL_LOGS: EmailLog[] = [
  { id: 'email-1', sellerId: 'seller-1', type: 'receipt', toEmail: 'sarah.m@gmail.com', subject: 'Your SellBop receipt — 1-on-1 Coaching Call', orderId: 'order-1', status: 'simulated', createdAt: '2024-04-10T14:31:00Z' },
  { id: 'email-2', sellerId: 'seller-1', type: 'receipt', toEmail: 'jared.k@outlook.com', subject: 'Your SellBop receipt — 1-on-1 Coaching Call', orderId: 'order-2', status: 'simulated', createdAt: '2024-04-08T09:16:00Z' },
  { id: 'email-3', sellerId: 'seller-1', type: 'download', toEmail: 'sarah.m@gmail.com', subject: 'Your download is ready — Notion Template Pack', orderId: 'order-5', status: 'simulated', createdAt: '2024-04-02T08:01:00Z' },
  { id: 'email-4', sellerId: 'seller-1', type: 'refund', toEmail: 'pastor.sue@newlife.org', subject: 'Your refund has been processed', orderId: 'order-15', status: 'simulated', createdAt: '2024-02-16T10:00:00Z' },
  { id: 'email-5', sellerId: 'seller-1', type: 'subscription_confirmed', toEmail: 'ryan.b@gmail.com', subject: 'Welcome to Systems Lab Membership!', orderId: 'order-10', status: 'simulated', createdAt: '2024-03-15T11:01:00Z' },
]

// ─── PAYOUTS ────────────────────────────────────────────────
export const DEMO_PAYOUTS: PayoutRecord[] = [
  { id: 'payout-1', sellerId: 'seller-1', amount: 43200, currency: 'usd', status: 'paid', periodStart: '2024-03-01T00:00:00Z', periodEnd: '2024-03-31T23:59:59Z', ordersIncluded: 14, paidAt: '2024-04-05T10:00:00Z' },
  { id: 'payout-2', sellerId: 'seller-1', amount: 38900, currency: 'usd', status: 'paid', periodStart: '2024-02-01T00:00:00Z', periodEnd: '2024-02-29T23:59:59Z', ordersIncluded: 11, paidAt: '2024-03-05T10:00:00Z' },
  { id: 'payout-3', sellerId: 'seller-1', amount: 67400, currency: 'usd', status: 'pending', periodStart: '2024-04-01T00:00:00Z', periodEnd: '2024-04-30T23:59:59Z', ordersIncluded: 6, paidAt: null },
]

// ─── ANALYTICS EVENTS (last 30 days) ────────────────────────
function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const DEMO_ANALYTICS_EVENTS: AnalyticsEvent[] = [
  ...Array.from({ length: 85 }, (_, i) => ({
    id: `evt-view-${i}`,
    sellerId: 'seller-1',
    productId: DEMO_PRODUCTS[i % 6].id,
    eventType: 'product_view' as const,
    buyerEmail: null,
    source: ['direct', 'twitter', 'google', 'instagram'][i % 4],
    metadata: {},
    createdAt: daysAgo(i % 30),
  })),
  ...Array.from({ length: 24 }, (_, i) => ({
    id: `evt-checkout-${i}`,
    sellerId: 'seller-1',
    productId: DEMO_PRODUCTS[i % 6].id,
    eventType: 'checkout_started' as const,
    buyerEmail: null,
    source: ['direct', 'twitter', 'google'][i % 3],
    metadata: {},
    createdAt: daysAgo(i % 28),
  })),
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `evt-purchase-${i}`,
    sellerId: 'seller-1',
    productId: DEMO_PRODUCTS[i % 6].id,
    eventType: 'purchase_completed' as const,
    buyerEmail: DEMO_CUSTOMERS[i % 10].email,
    source: ['direct', 'twitter'][i % 2],
    metadata: { amount: DEMO_PRODUCTS[i % 6].price },
    createdAt: daysAgo(i % 28),
  })),
]

// ─── REVENUE CHART DATA ──────────────────────────────────────
export function getDemoRevenueChartData() {
  const months = ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
  const values = [18200, 24500, 31000, 28900, 38900, 43200, 67400]
  return months.map((month, i) => ({ month, revenue: values[i] }))
}

export function getDemoSalesChartData() {
  return Array.from({ length: 30 }, (_, i) => ({
    day: i + 1,
    sales: Math.floor(Math.random() * 5) + (i < 10 ? 1 : i < 20 ? 2 : 3),
    revenue: (Math.floor(Math.random() * 5) + 1) * 2900,
  }))
}
